version: '3'
services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: mysql_mall
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  redis:
    image: redis:latest
    restart: always
    container_name: redis_mall
    ports:
      - 6379:6379